baseURL = 'https://blog.gcourtot.fr/'
languageCode = 'fr-FR'
title = 'Bonjour la toile'
theme = "papermod"

[params]
  ShowToc: true
  ShowReadingTime = true
  outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
