baseURL = "https://blog.gcourtot.fr/"
languageCode = "fr"
title = "Mon blog"
theme = "cactus"
googleAnalytics = ""

[params]
  author = "Guillaume Courtot"
  description = "Un blog pour ne rien dire, mais le dire quand même."
