baseURL = 'https://blog.gcourtot.fr/'
languageCode = 'fr-FR'
title = 'Bonjour la toile'
theme = "papermod"

[params]
  ShowToc = true
  ShowReadingTime = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 20
